### ISSUE TITLE
Bikeshed: Is "prerender" the right terminology for the new browsing context type

### ISSUE THREAD

**Issue by bokand** [WICG/nav-speculation#12]
This came up in https://github.com/jeremyroman/alternate-loading-modes/pull/11#discussion_r531108170. Given that a prerendering browsing context will host portaled documents, which can be adopted from active documents, and there's potential to use this for fenced frames, should we consider a name that isn't tied to prerendering?

FWIW - given how far off fenced frames appear and portals' predecessor adoption is still very theoretical, I think we can kick this can down the road. But leaving this here for context and in case others have thoughts.

**Comment by domfarolino** [comment]
"Preview" browsing context?

**Comment by jeremyroman** [comment]
Preview might evoke the ideal of a visual preview. I suspect we'll land on prerender because it's already a known term, but some other ideas:

* an analogy about not being presented yet: *backstage* (as in, waiting in the wings) or *on deck*
* an analogy about the future: *speculated* or *anticipated*
* an analogy about restrictions: *confined*
* an analogy about hot/cold like an engine: *warm* or *warmed*

**Comment by bokand** [comment]
I particularly like "speculative" since it captures the essential difference for prerendering/portals; however, do we still have aspirations of fitting fenced frames into it? If so, then I think the real distinction is more to do with restrictions so perhaps "confined" or "isolated" or something to that effect might be more apt.

**Comment by domfarolino** [comment]
Speculative doesn't seem to capture portals very well, since it is not a speculative request, and is intended to be shown to the user in some scaled/previewed form right?

**Comment by bokand** [comment]
It's speculative in the sense that it is meant to become a top-level browsing context and may not be activated by the user.

**Comment by domfarolino** [comment]
The activation part perhaps, that makes sense. Spec-wise it will still be a top-level browsing context.

**Comment by bokand** [comment]
Sorry,

> meant to become a top-level browsing context 

Was supposed to be 

> meant to become the active top-level browsing context.

It's speculative in the sense that it's not embedded in the current document's frame tree (like an iframe is) and may never be put into an unrestricted, active browsing context.

**Comment by shivanigithub** [comment]
> I particularly like "speculative" since it captures the essential difference for prerendering/portals; however, do we still have aspirations of fitting fenced frames into it? If so, then I think the real distinction is more to do with restrictions so perhaps "confined" or "isolated" or something to that effect might be more apt.

Yes, fenced frames do hope to use this header and it sounds reasonable to create a new value like 
`Supports-Loading-Mode: fenced-frame`
I am more inclined to treat fenced frames separately because they are unique in that they are always nested (no activation) and there are surely many ways in which they differ with the other use cases e.g. fenced frames would be treated as a sandboxed (unique origin) frame.
