### ISSUE TITLE
Provide a mean to defer Javascript execution

### ISSUE THREAD

**Issue by AndrewKGuan** [WICG/nav-speculation#129]
Hi,
I hope this is the right place to share this idea.  Would it be possible/nice to have a way for developer users to indicate that they want Javascript on a page to be deferred until showing via the API?  This can alleviate the concern of untimely execution of the scripts and reduce the device/browser load during the prerendering process.  It could be as simple as a flag inside the speculation rule:
`{
  "prerender": [
    {"source": "list", "urls": ["foo.html"], "deferScript" : true}
  ]
}`

**Comment by jeremyroman** [comment]
Pasting a few thoughts from an internal thread on the same subject:

- Just not executing script at all is likely to stall pretty early, when the first non-async/defer/module `<script>` is hit. We could potentially scan past this for finding subresources (this is likely to work okay in practice), but we can't actually build the DOM because we might have to undo it if the script does something strange, e.g. using document.write -- and we have no machinery for undoing it. Even the subresource fetches are a little funny, but something we have plenty of precedent for.

- Even absent that, many sites are going to need to run script to approach their final state -- which is the main selling point of prerendering. If the site doesn't get close, we might be better off with single-resource prefetch or prefetch with subresources (~NSP). Much like iframes, some scripts are likely inessential but it might be harder to know what those are. Potentially sites could mark them with an attribute, though with slightly more work they could do the same today by inspecting `document.prerendering` and inserting them only when prerendering ends, so this would mostly be syntactic sugar.

- Trying to automatically do this where the first issue doesn't apply, e.g. delaying only `<script async>`, might run the risk of making authors who want their core scripts to prerender correctly optimize their site for prerendering but simultaneously make them worse for non-prerendering, where asyncness might be appropriate. We should think about perverse incentives.

- Allowing the requester to choose whether and which scripts run is a potential communication channel and somewhat remotely a way to force a site to misbehave by manipulating the timing of its load. Probably not a showstopper but requires thought.

Happy to reopen this issue if we think we're likely to discuss/pursue this in more depth, but closing for now.
