### ISSUE TITLE
Race condition: activation before response?

### ISSUE THREAD

**Issue by noamr** [WICG/nav-speculation#145]
Envision the following scenario:
- User agent initiates a prerender (e.g. from the URL bar)
- The request is sent, with `Sec-Purpose: Prerernder` header etc.
- User activates the prerender, before the response came back
- The response comes back with 204/503, to prevent prerendering

The current spec would reach an error state when it tries to access the `prerendering browsing context`'s `active document` in the 204 case, and would show the user the error in the 503 case, even though a new request would have succeeded.

I see the options as:

1. Ignore the ongoing request and start a new one - could miss out on some prerendering benefits of starting the request early
2. Wait until the response comes back and only start a new request if it's an error - could make prerendering slower than regular navigation in some scenarios.
3. ?

I'm in favor of (1) - to specify that a browsing context can be activated only if it has an active document. 
From my experimentation, the implementation currently does (2). I'm not sure the difference between the two is entirely observable.

**Comment by domenic** [comment]
> The current spec would reach an error state when it tries to access the `prerendering browsing context`'s `active document`

I'm not sure exactly what you mean by error state, but I think it would not have a problem at that state. The active document is the initial about:blank Document, at first.

(We state in explainers that there is no initial about:blank Document for prerendering BCs, but that's not quite true. Instead the intention was that the initial about:blank Document is not observable to web developer code.)

So I think the current spec would:

- Send a Sec-Purpose: prefetch header
- Activate the initial about:blank Document, firing an (unobservable) prerenderingchange event on it
- Mark it as not a prerendering BC
- Pass all the checks in https://wicg.github.io/nav-speculation/prerendering.html#no-bad-navs since we are no longer a prerendering BC

so basically we would show you whatever is currently shown for a 204 or 503.

Probably we should indeed prevent this since without the Sec-Purpose header maybe we would have gotten a more useful response.

(1) and (2) are observably different in the case where the server takes a long time to give a 200. (Or other success status code.) (1) results in two fetches to the server, and (2) results in a single fetch to the server.

In terms of performance, let's be more precise with the tradeoffs. (1) is:

- Faster than (2) in cases where the server responds with an error status, slowly. (We start the second request sooner.)
- Slower than (2) in cases where the server responds with a success status, slowly. (We throw away the head start on the first request in order to begin a second request.)

My instinct is that this makes (2) a better tradeoff, if we envision a world where only a small percentage of servers want to deny prerendering, but a larger percentage of servers has a slow time-to-first-byte. But I am not sure.

**Comment by noamr** [comment]
> > The current spec would reach an error state when it tries to access the `prerendering browsing context`'s `active document`
> 
> 
> 
> I'm not sure exactly what you mean by error state, but I think it would not have a problem at that point. The active document is the initial about:blank Document, at first.
> 
> 
> 
> (We state in explainers that there is no initial about:blank Document for prerendering BCs, but that's not quite true. Instead the intention was that the initial about:blank Document is not observable to web developer code.)
> 
> 
> 
> So I think the current spec would:
> 
> 
> 
> - Send a Sec-Purpose: prefetch header
> 
> - Activate the initial about:blank Document, firing an (unobservable) prerenderingchange event on it
> 
> - Mark it as not a prerendering BC
> 
> - Pass all the checks in https://wicg.github.io/nav-speculation/prerendering.html#no-bad-navs since we are no longer a prerendering BC
> 

Correct, I made a mistake in my analysis, it would show about:blank which is still undesired.

> 
> 
> so basically we would show you whatever is currently shown for a 204 or 503.
> 
> 
> 
> Probably we should indeed prevent this since without the Sec-Purpose header maybe we would have gotten a more useful response.
> 
> 
> 
> (1) and (2) are observably different in the case where the server takes a long time to give a 200. (Or other success status code.) (1) results in two fetches to the server, and (2) results in a single fetch to the server.
> 
> 
> 
> In terms of performance, let's be more precise with the tradeoffs. (1) is:
> 
> 
> 
> - Faster than (2) in cases where the server responds with an error status, slowly. (We start the second request sooner.)
> 
> - Slower than (2) in cases where the server responds with a success status, slowly. (We throw away the head start on the first request in order to begin a second request.)
> 

Also in the case of (1) we didn't degrade from the current behavior in the worst case.

> 
> 
> My instinct is that this makes (2) a better tradeoff, if we envision a world where only a small percentage of servers want to deny prerendering, but a larger percentage of servers has a slow time-to-first-byte. But I am not sure.

Maybe an option (3) is to "race" the two requests? As in Start a new one but accept the old one if it is successful?

Anyways the current implementation does (2) and it's perhaps simple enough but should be speced
