### ISSUE TITLE
What's the behavior of client hints and prerendering?

### ISSUE THREAD

**Issue by miketaylr** [WICG/nav-speculation#150]
I'm curious how Client Hints should behave in a prerendered browsing context, specifically what happens with the Accept-CH cache and [Critical-CH](https://github.com/WICG/client-hints-infrastructure/blob/main/reliability.md#critical-ch): 

If my Accept-CH cache is empty, and my browser prerenders `example.com` which sends back `Accept-CH: sec-ch-ua-device-model; Critical-CH: sec-ch-ua-device-model` - what's the expected behavior? 2 prerenders? Or just 1, but the page reloads when the prerendered browser context is activated?

**Comment by nhiroki** [comment]
How the retry for Critical-CH is defined in the navigation algorithm? Basically prerendering navigation [follows the reguler navigation algorithm](https://wicg.github.io/nav-speculation/prerendering.html#create-a-prerendering-browsing-context), so if it works just like redirection, 1 prerender should be created.

cc: @yoavweiss for the Client Hints spec.

**Comment by noamr** [comment]
IIUC, the client hints (including Critical-CH) would be resolved during the navigation fetch, and activation would not re-send this information.

Considering [Device-Memory](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Device-Memory), this can lead to a scenario, for example, where the available memory at the time of prerendering is high so a complex version of the page is served, and the memory is a lot lower when activating so there would be some mismatch. I think this is a good thing! For example, the prerendered page itself might be what's causing this additional memory use - so sending this request again might be misleading with regards to available memory. The same goes for [Downlink](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Downlink) - perhaps the prerendered page is hogging the network?

Some other scenarios, like the deprecated DPR and Viewport-Width, should not change between prerendering and activation anyway.

In the case of [Save-Data](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Save-Data), the last thing you want to do is reload the page if what you're doing is trying to save data. Perhaps prerendering should be prohibited at all in low-data modes, regardless of client hints.

**Comment by yoavweiss** [comment]
> Considering [Device-Memory](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Device-Memory), this can lead to a scenario, for example, where the available memory at the time of prerendering is high so a complex version of the page is served, and the memory is a lot lower when activating so there would be some mismatch. I think this is a good thing! For example, the prerendered page itself might be what's causing this additional memory use - so sending this request again might be misleading with regards to available memory. The same goes for [Downlink](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Downlink) - perhaps the prerendered page is hogging the network?

Small correction but neither Device-Memory not Downlink refer to the available memory or bandwidth. Device-Memory is static, so always gives you the machine's available memory, in well-specified buckets. Downlink is more dynamic and can vary as bandwidth changes, but it's an estimate of the overall bandwidth, not the available one.

I think that @miketaylr's question was regarding how prerendering should behave in the face of Critical-CH that forces an internal redirect to the same resource, with the right CH headers (so a scenario where e.g. Mobileness was not part of the initial request, but it's critical in order to render the right site).
In this case, I think the right behavior should be for the internal redirect to happen ASAP (similar to a not-prerendered navigation), in order to increase the chances of the right document being available at activation time.

I agree that this doesn't impact compat right now, but is probably something which will impact compatibility (e.g. potentially create flash-of-wrong-content-negotiation) if we were to change this behavior (to the wrong one :P) after shipping.

@miketaylr - As specified, I don't think that Critical-CH's processing model explains how it ties into HTML's navigation algorithms. It might be worthwhile to do that, and clarify this along the way. (Assuming we all agree that what I consider the "right" behavior is indeed what we should do)

**Comment by noamr** [comment]
> Small correction but neither Device-Memory not Downlink refer to the available memory or bandwidth. Device-Memory is static, so always gives you the machine's available memory, in well-specified buckets. Downlink is more dynamic and can vary as bandwidth changes, but it's an estimate of the overall bandwidth, not the available one.

Oh good to know, I misunderstood some of the documentation. So this is event clearer that there's no need to resend the second CH request on activation.

> 
> I think that @miketaylr's question was regarding how prerendering should behave in the face of Critical-CH that forces an internal redirect to the same resource, with the right CH headers (so a scenario where e.g. Mobileness was not part of the initial request, but it's critical in order to render the right site). In this case, I think the right behavior should be for the internal redirect to happen ASAP (similar to a not-prerendered navigation), in order to increase the chances of the right document being available at activation time.

Considering that also memory/downlink don't change between navigation and activation, are there any situations where those hints *would* change?

> 
> I agree that this doesn't impact compat right now, but is probably something which will impact compatibility (e.g. potentially create flash-of-wrong-content-negotiation) if we were to change this behavior (to the wrong one :P) after shipping.

So to iterate, it would only create this flash if we decide to redirect upon activation, which we shouldn't :)

**Comment by yoavweiss** [comment]
> So to reiterate, it would only create this flash if we decide to redirect upon activation, which we shouldn't :)

I agree that we shouldn't, which means that we need to consider Critical-CH before the page is activated. Otherwise, the effect would essentially be a redirect upon activation.
