### ISSUE TITLE
<link rel="next/prev"> support & reflection/DOM

### ISSUE THREAD

**Issue by slightlyoff** [WICG/nav-speculation#220]
Several properties of the design outlined in this post are surprising, and I would have expected to come up in TAG review:

https://developer.chrome.com/blog/prerender-pages/

First, it doesn't appear that the existing `next` and `prev` values for `rel` (once [supported by Googlebot](https://developers.google.com/search/blog/2011/09/pagination-with-relnext-and-relprev)) are operable here. This is surprising! 

It's also surprising that the `type="speculationrules"` does not come with some sort of DOM or reflection for the values included in it. If such script elements are added by DOM operations, what happens? How can one construct a merged view without fully re-parsing? It seems like half an API.

**Comment by domenic** [comment]
Hi Alex!

I can't comment on what the TAG should have thought, but I'll address your points at least.

It's not clear how the fact that Googlebot uses these to discover new pages to crawl, would relate to a browser using these to trigger navigational preloading. But as explained in https://github.com/WICG/nav-speculation/blob/main/triggers.md#extending-the-link-element, we believe the `<link>` element is not a good trigger for the type of preloading discussed in this repository. This applies even to the explicit existing rels of `prefetch` and `prerender`. Then, adding in support for the implicit rels `next` and `prev`, and triggering some sort of navigational preloading based off them, would be extra surprising. It would likely have compat concerns beyond those explained in the linked explainer. E.g., I don't think fanfic sites using `<link rel=next>` for the next chapter will necessarily want to trigger chapter 2's server-side analytics (for prefetch) or client-side ad/impression logging (for prerender) once you load chapter 1.

Regarding dynamic modification of speculation rules, this is certainly possible today, by adding/removing `<script>` elements, or changing their text content. An API for manipulating that text content in a structured way instead of having to parse-then-reserialize, or for viewing some sort of composite of all different speculation rules `<script>`s on the page, is certainly conceivable. But it hasn't been something we've heard from partners as being a blocker for achieving the experiences they want. And given how hard it generally is to design good DOM-reflection APIs (cf. the unfortunate CSSOM), we haven't invested much in that area. (This is the same as the story for import maps, by the way: https://github.com/WICG/import-maps#programmatic-api.)

If you have heard from some potential users that they're finding speculation rules difficult to adopt due to this lack of API, we'd love to learn more. It's possible a small JavaScript library could make this easier for them, or of course we'd love the Edge team's help in specifying and building such an addition, perhaps after a JavaScript library has helped us settle on the right API shape.
