### ISSUE TITLE
More flexibility with `speculation`, instead of `speculationrules`?

### ISSUE THREAD

**Issue by j9t** [WICG/nav-speculation#229]
Is there time and openness to reconsider the chosen attribute value naming?

From reading the documentation it seems that just `speculation` might

* suffice (why go long if short works, too),
* be consistent with more standard attribute values (most attribute values seem to use a one-word form), and
* be more extensible (more use cases could be covered, say, if speculation would also at some point get configuration or other options, beyond rules).

That is, and unless this misses something important, could we consider `<script data-type=speculation>` or, if standardizable (see #228), `<script type=speculation>`?

**Comment by jeremyroman** [comment]
Thanks for your feedback.

My thinking was that a name that was longer would be easier to refer to and search for, especially since it appears in places besides the `type` attribute (e.g., the `application/speculationrules+json` MIME type).

While most attribute values do are formatted [like enumerations](https://w3ctag.github.io/design-principles/#casing-rules), the existing example of `type="importmap"` made concatenated, rather than hyphenated, seem the more consistent to me.

Choosing good names is hard, and while I'm not sure the name chosen here is perfect, I'm also not sure that there is strong enough motivation to change it at this point.
