### ISSUE TITLE
`prefetch-src` is gone

### ISSUE THREAD

**Issue by noamr** [WICG/nav-speculation#235]
See https://github.com/w3c/webappsec-csp/pull/582
Now prefetch uses "least restrictive" directive from CSP.
I believe prerender should use `default-src` (since I believe `navigate-to` is not happening?).

/cc @mkwest

**Comment by jeremyroman** [comment]
It feels like this description erases the distinction between the behavior you're defining for `<link rel=prefetch>`, which is essentially a fetch that goes to a null destination with the aim of populating the HTTP cache, and the notion of prefetch for navigation which this spec defines.

As it applies to this case, the prefetch destination is known and it does have an effect because it modifies how navigation works if a request matches. Maybe that's fine and dropping `prefetch-src` makes sense there too, but I don't think it's a given.

Prerender is even more interesting because it can cause script execution and further subrequests. It feels odd for `default-src` to be the only control developers have over that through CSP, as it's more similar to `frame-src` in that regard (even though that directive isn't directly applicable).

**Comment by noamr** [comment]
The idea of most CSP destinations, like `script-src`, is to protect the current document.
Speculation rules don't really affect the current document, they're more like `navigate-to` in that way.
Arguably, the only way you could expose from speculation rules is exfiltration, which `default-src` can protect against.

But we should have a clear direction with this. Since `<link rel=prefetch>` is dropping `prefetch-src`, it's not an obvious way forward.

/cc @mkwst

**Comment by domenic** [comment]
I'm happy to accept that the WebAppSec group has decided that preventing navigational prefetches is only possible via default-src. We can rip out all of our mentions of it, I suppose.

**Comment by noamr** [comment]
> I'm happy to accept that the WebAppSec group has decided that preventing navigational prefetches is only possible via default-src. We can rip out all of our mentions of it, I suppose.

I'm not sure I would count this as a decision of the WebAppSec group. This is more of a proposal.

**Comment by domenic** [comment]
Well, it got merged into their specs, so I thought it was decided...

**Comment by noamr** [comment]
> Well, it got merged into their specs, so I thought it was decided...

It was merged with link-rel prefetch in mind, I think navigational prefetch and especially prerender is slightly different.
But perhaps a good first step would be to not have CSP support at all in this and keep it as an open issue.

**Comment by domenic** [comment]
Yeah, that seems like the right move to me. Prefetch-src was never implemented anywhere anyway, and I prefer having our spec integrate with reality than with a speculative CSP spec. If in the future WebAppSec is interested in adding more stuff to CSP for navigational prefetch, and has some commitment to actually implement them, we'll be standing by and ready to change our initiator.
