### ISSUE TITLE
forbidden JavaScript API 

### ISSUE THREAD

**Issue by kapustina-oks** [WICG/nav-speculation#299]
Hello, when I try to configure the speculation rules script I get this error "The prerendered page used a forbidden JavaScript API that is currently not supported. (Internal Mojo interface: extensions.mojom.EventRouter)" and all my preprocessing pages are not pre-rendered. 

Also I have tried to test you example on https://prerender-demos.glitch.me/ page, and there is the same problem

but in incognito mode everything works fine!

Could you tell me how to fix this issue?

<img width="1380" alt="Снимок экрана 2024-02-14 в 16 48 30" src="https://github.com/WICG/nav-speculation/assets/70973622/57819a24-83c4-45b1-8a5b-3401b8ba8bcd">
<img width="1680" alt="Снимок экрана 2024-02-14 в 16 49 45" src="https://github.com/WICG/nav-speculation/assets/70973622/947d3525-12b0-4470-bbe3-d67da0484fdb">

**Comment by jeremyroman** [comment]
Since this is a Chromium-specific question, this tracker probably isn't the best place to ask. Nonetheless, most likely you have an extension installed which is trying to register event listeners while prerendering is taking place. It works in incognito because such extensions are not running there. https://chromium-review.googlesource.com/c/chromium/src/+/5051467 should have made this less of an issue in Chromium, so try in Chrome 122 (currently beta, though it will be stable in a week or so) or above.
