### ISSUE TITLE
Clarify Speculation Rules header interaction with CSP

### ISSUE THREAD

**Issue by SulemanAhmadd** [WICG/nav-speculation#327]
We have seen that pages that have strict CSP headers (strict-dynamic) set on a page, refuse to load speculation rules from the link in the header.

The specification talks about applying CSP for speculation rules that are added by an inline script. Its unclear from the spec whether the same CSP directive apply to rulesets retrieved using the header?

The `inline-speculation-rules` CSP value allows inclusion of speculation rules from inline `<script>` tags, does the same apply for rules dynamically loaded using the Speculation Rules header?

**Comment by domenic** [comment]
/cc @jeremyroman to check my reading

> We have seen that pages that have strict CSP headers (strict-dynamic) set on a page, refuse to load speculation rules from the link in the header.

Can you provide a demo page?

> Its unclear from the spec whether the same CSP directive apply to rulesets retrieved using the header?

It should not apply, by my reading of the spec, since such fetches use the "speculationrules" request destination.

> The `inline-speculation-rules` CSP value allows inclusion of speculation rules from inline `<script>` tags, does the same apply for rules dynamically loaded using the Speculation Rules header?

Per spec, it only affects inline speculation rules scripts.

**Comment by SulemanAhmadd** [comment]
We are working with a partner. Unfortunately, they mentioned that they dont have access to the specific error producing page anymore (they reverted the speculation rules change) so we cannot reproduce at the moment, but they did share the following screenshot:

<img width="659" alt="image" src="https://github.com/user-attachments/assets/05599266-ff2c-433c-b824-98fadbe89b3c">

The Speculation-Rules header for that page was: `Speculation-Rules: "/cdn-cgi/speculation-rules?url=www.wthubspot.com/"`

So its obvious that [www.wthubspot.com](http://www.wthubspot.com/) is not part of their CSP policy. But, should we clarify in the specification that CSP directives are respected for ruleset fetches? Is this intended behaviour?

**Comment by jeremyroman** [comment]
> > Its unclear from the spec whether the same CSP directive apply to rulesets retrieved using the header?
> 
> It should not apply, by my reading of the spec, since such fetches use the "speculationrules" request destination.

But that request destination has `script-src` as its effective directive: https://wicg.github.io/nav-speculation/speculation-rules.html#content-security-policy-patches-effective-directive

I would have expected the `'self'` part of the directive to allow this, though. My first guess here is that `'strict-dynamic'` is causing trouble, since it causes a nonce or hash to be _required_ for any fetch respecting the directive. At the moment that's simply incompatible, but maybe we should fix it.

The two basic options would seem to be:
* ignore `'strict-dynamic'` for speculation rules (it doesn't apply to other resource types)
* expand `Speculation-Rules` to provide a place for supplying a nonce or hash, and then expect authors to use that (e.g., `Speculation-Rules: "/cdn-cgi/speculation-rules?url=www.wthubspot.com/"; nonce="nFShhc..."`

Honestly I suspect the former is correct, assuming this is indeed the problem, but would want a CSP expert's take, too.

**Comment by SulemanAhmadd** [comment]
> expand Speculation-Rules to provide a place for supplying a nonce or hash, and then expect authors to use that

How would website owners specify that nonce? The rules retrieved from the header do not involve specific a `script` tag. Also, this option would make CDN based deployments using the header painful.

> ignore 'strict-dynamic' for speculation rules (it doesn't apply to other resource types)

Have to see if there are no security implications. Looks okay to me on the surface.

Other than that, the wording on the draft at https://wicg.github.io/nav-speculation/speculation-rules.html#content-security-policy-patches-effective-directive, is very confusing. Seems incomplete?

**Comment by jeremyroman** [comment]
> > expand Speculation-Rules to provide a place for supplying a nonce or hash, and then expect authors to use that
> 
> How would website owners specify that nonce? The rules retrieved from the header do not involve specific a `script` tag. Also, this option would make CDN based deployments using the header painful.

It would look something like the example I gave later on (appearing as a parameter in the header); this would be a new addition.

I certainly agree that this would make the CDN case harder. The CDN would have to parse and potentially modify the CSP header, if one exists.

It already potentially has to, because `script-src` might not include `'self'`, but in practice I'm pretty sure authors usually do include it. If we did make CDNs have to do this, it wouldn't be entirely new (if you use a CDN to inject a telemetry script or similar into the response body today, it's also necessary to make sure it's compliant with the CSP).

> > ignore 'strict-dynamic' for speculation rules (it doesn't apply to other resource types)
> 
> Have to see if there are no security implications. Looks okay to me on the surface.

There are some security implications in contrived cases, at least, but I _think_ they're fairly slight in practice.

> Other than that, the wording on the draft at https://wicg.github.io/nav-speculation/speculation-rules.html#content-security-policy-patches-effective-directive, is very confusing. Seems incomplete?

All of section 2 is just patches against [[CSP]](https://w3c.github.io/webappsec-csp/). This particular section should just adds one switch case to [this algorithm](https://w3c.github.io/webappsec-csp/#effective-directive-for-a-request).

In theory making the `Speculation-Rules` header CSP exempt altogether would also work, but I don't think that's likely to be a good path forward.

**Comment by SulemanAhmadd** [comment]
> If we did make CDNs have to do this, it wouldn't be entirely new (if you use a CDN to inject a telemetry script or similar into the response body today, it's also necessary to make sure it's compliant with the CSP).

Fair point. I believe then it would be another extra check for CDN deployments to make sure the nonce matches the `strict-dynamic` directive nonce value for all requests.

The least friction solution in my opinion would be to ignore `strict-dynamic` for Speculation Rules injected through the header.

**Comment by jeremyroman** [comment]
I have been able to reproduce what I guessed in https://github.com/WICG/nav-speculation/issues/327#issuecomment-2289932980, with a minimal header of `Content-Security-Policy: 'self' 'strict-dynamic'` (and removing `'strict-dynamic'` causes the load to succeed).

**Comment by jeremyroman** [comment]
Quick update here -- still need to discuss what is feasible here from our security team's perspective, but summer vacations are affecting availability.

**Comment by SulemanAhmadd** [comment]
Thanks @jeremyroman, looking forward to it. Some site owners have responded back that unless they modify their CSP header to remove `strict-dynamic`, it has been affecting their Google PageSpeed rating as well due to the console errors.
