### ISSUE TITLE
Handle when referrerpolicy is the empty string?

### ISSUE THREAD

**Issue by mfalken** [WICG/nav-speculation#51]
The current spec has steps:

> Let referrerPolicy be the current state of el’s referrerpolicy attribute.
> If the list of sufficiently-strict speculative navigation referrer policies does not contain referrerPolicy, then return.

But I think `referrerPolicy` is the empty string if it's not specified, which isn't on the list. I believe the intention is for this to be treated as "strict-origin-when-cross-origin" but I don't know if `referrerPolicy` becomes that automatically without additional spec steps. cc @domfarolino

**Comment by mfalken** [comment]
The spec also seems to just take use the element's attribute only and doesn't take into consideration the document's referrer policy.

Currently Blink seems to ignore the referrerpolicy attribute on <link rel=prerender> and just use the document's one:
https://source.chromium.org/chromium/chromium/src/+/master:third_party/blink/renderer/core/loader/prerender_handle.cc;l=56-57;drc=f981ba80746e6eb482052394d298b6d3d971582e

**Comment by nhiroki** [comment]
> Currently Blink seems to ignore the referrerpolicy attribute on and just use the document's one:
> https://source.chromium.org/chromiumz/chromium/src/+/master:third_party/blink/renderer/core/loader/prerender_handle.cc;l=56-57;drc=f981ba80746e6eb482052394d298b6d3d971582e

The current implementation completely ignores the referrer passed from the renderer and uses the default value of navigation [here](https://source.chromium.org/chromium/chromium/src/+/master:content/browser/prerender/prerender_host.cc;l=286;drc=55258c7d7fa2ba4ad5b2c74d09cc493042eb31a9) (`NavigationController::LoadURLParams::referrer` is not set).

**Comment by mfalken** [comment]
Yes, I'm working on that for Prerender2 :) I was looking at what NSP does with the attribute as that's the current impl of <link rel=prerender>. I should have been more clear.

**Comment by nhiroki** [comment]
Ah, I see!  I assumed we were talking about the current tentative implementation of Prerender2 :)

**Comment by mfalken** [comment]
CL is incoming :) https://chromium-review.googlesource.com/c/chromium/src/+/2744899

**Comment by jeremyroman** [comment]
@domfarolino wrote this text, I think. It certainly should inherit from the document if unspecified, though I think that might be done at another layer; I'm not sure.

**Comment by domfarolino** [comment]
So there seems to be two problems pointed out here:
 - The fact that the empty string state is not in the [list of sufficiently-strict referrer policies](https://jeremyroman.github.io/alternate-loading-modes/index.html#list-of-sufficiently-strict-speculative-navigation-referrer-policies)
 - The fact that the document's referrer policy _appears to be ignored_

The first one is certainly an issue. The referrer policy enumerated attribute indeed defaults to the empty string state, which does not appear in the list of allowed policies, so all prerenders with no explicit attribute will be failed to fetch. This can be remedied by adding `""` to the list of allowable policies.

The second one is more interesting. Falling back to the request's client's referrer policy is done in Fetch, so that you don't have to supply an explicit referrer policy for every single request in HTML, or other specs. However, if we just relied on falling back to the document's referrer policy in Fetch, then we risk the document's policy being looser than `strict-origin-when-cross-origin`, which is the baseline we've decided should be used for prerender. So it's possible that when `referrerpolicy` is not provided and does default to the empty string, we will have to do some up-front calculation as to whether or not we can rely on the document's referrer policy. The current spec is failing to do this, so I'll work on fixing that somewhere.

**Comment by jeremyroman** [comment]
I would think the right fix would be to use the fully resolved referrer policy (which should not longer be `""` after applying document and platform defaults) to make the decision. Is that what you're suggesting?

**Comment by domfarolino** [comment]
> I would think the right fix would be to use the fully resolved referrer policy (which should not longer be "" after applying document and platform defaults) to make the decision. Is that what you're suggesting?

In that case that there is no `referrerpolicy` provided on the `<link>` then yes, that is what I'm suggesting. Of course if one is provided that matches a policy in the allowable policy list, then we can just go with that

**Comment by domenic** [comment]
Closing since we removed the spec for `<link rel=prerender>` since we ended up not using that as a trigger.
