### ISSUE TITLE
Response to request for TAG review

### ISSUE THREAD

**Issue by rhiaro** [WICG/nav-speculation#56]
Hi folks,

Thanks for [requesting an early review from the TAG](https://github.com/w3ctag/design-reviews/issues/611). Sorry it took us a while to get to this; I have some initial feedback and questions.

You have described this as an alternative to Resource Hints. As far as I can tell, Resource Hints is still an in-progress WD, so is there a reason you can't update/extend that to be in line with the privacy-preserving goals and increased flexibility of Speculation Rules rather than starting from scratch? If Resource Hints is to become a recommendation, what functionality is duplicated by Speculation Rules? Does it make sense for the two to co-exist or would Speculation Rules make Resource Hints redundant?

I appreciate the thoughtful responses to the Security & Privacy questionnaire, although I think there is scope for stronger language about tracking prevention. Also the discussion of developer tooling looks great.

I have a couple of questions which probably just reveal my ignorance about the status quo here. Does a prefetch/prerender appear as normal web traffic to the destination or is it recogniseable as a prefetch (ie. what sort of effect does this have on analytics, if any)? Does this take into account prefetching/prerendering pages that immediately trigger an interaction with the user via the browser UI, like notifications, geolocation permissions etc? Can the prefetched origin get any other data about the user's current browsing context via js APIs way?

What kind of heuristics does the UA use to speculate, and are these transparent to authors and end users?

There's a bit in the privacy & security questionnaire about the UA's heuristics potentially revealing user data to the origin which could be a concern (particularly from a fingerprinting standpoint). Have you thought through what sort of rules a malicious origin might set in order to get as much leaked data as possible from the UA?

Is there some way for the user to have the final say in whether/which origins can be prefetched? A permissions prompt is probably overkill, but maybe a browser setting.

**Comment by domfarolino** [comment]
I have a few answers, but @jeremyroman probably has the rest:

> Does a prefetch/prerender appear as normal web traffic to the destination or is it recogniseable as a prefetch (ie. what sort of effect does this have on analytics, if any)?

Prerender and prefetch requests will be sent wth the `Sec-Purpose: Prefetch` header (this is not yet in our spec, but coming soon), so in that sense they are distinguishable. In terms of analytics, prefetchs will never run JavaScript. Prerenders will run JavaScript with the following caveats:
 - `document.loadingMode` will be `prerendering` so that JS can distinguish between normal and prerendering loading modes, as to perhaps not track analytics in `prerendering` mode
 - Cross-origin prerender responses are immediately thrown away if the cross-origin does not opt-in to uncredentialed prerendering, meaning JavaScript on these sites will not run unless the origin says "Yep we can support this". I think this should mitigate some cross-origin analytics concerns

> Does this take into account prefetching/prerendering pages that immediately trigger an interaction with the user via the browser UI, like notifications, geolocation permissions etc?

Prefetch doesn't run JS, so I think this is not an issue there.

For prerendering, our plan is to audit all browser APIs that cause some UI or user interaction and delay their execution until the prerender is activated (that is, delayed until the prerendered page is shown to the user). This can be seen in https://jeremyroman.github.io/alternate-loading-modes/index.html#delay-async-apis. I don't think we're finished auditing all cases yet.

> Can the prefetched origin get any other data about the user's current browsing context via js APIs way?

With prefetches I do not believe so no, because they do not execute script. Prerenders are stored in a new top-level browsing context entirely isolated from all other contexts specifically for the concern you raise, so I believe the prerender cannot learn anything about any other pages or browsing contexts. One thing we're currently working on is ensuring that the prerendered page cannot contaminate the HTTP cache partition used by non-prerendered pages with the same origin. We'll be taking care of this by providing some sort of prerendering-specific [network partition key](https://fetch.spec.whatwg.org/#network-partition-keys). We have a similar concern for cookies that we're working to address as well.

**Comment by jeremyroman** [comment]
> Hi folks,
> 
> Thanks for [requesting an early review from the TAG](https://github.com/w3ctag/design-reviews/issues/611). Sorry it took us a while to get to this; I have some initial feedback and questions.
> 
> You have described this as an alternative to Resource Hints. As far as I can tell, Resource Hints is still an in-progress WD, so is there a reason you can't update/extend that to be in line with the privacy-preserving goals and increased flexibility of Speculation Rules rather than starting from scratch? If Resource Hints is to become a recommendation, what functionality is duplicated by Speculation Rules? Does it make sense for the two to co-exist or would Speculation Rules make Resource Hints redundant?

I think the two could coexist. The design of Resource Hints (using the `<link>` element and HTTP `Link` response header) is simple but doesn't seem to naturally generalize to meet some of the directions we anticipate. I think ideally Speculation Rules would be powerful enough to offer a superset of the existing functionality of the Resource Hints surface.

To give one example, consider the "requires anonymous IP when cross-origin" constraint. The natural way to apply this might be something like:

```html
<link rel="prefetch" href="//example.com/" requiresanonymousipwhencrossorigin>
```

Because unrecognized HTML attributes are generally ignored, including in the case of the Resource Hints spec, this would cause UAs which implemented Resource Hints but not this addition to erroneously fetch without anonymizing the client IP, contrary to the author's expectations. This could be worked around with effort by using some form of feature detection or UA sniffing, but this sort of fail-open is not great for security/privacy enhancing features.

To give a second example, authors may be more likely to adopt this functionality if they can make a blanket pronouncement that certain links are likely to be clicked, so that rather than the author being responsible for synchronizing the `<head>` and `<body>` to reflect this, they can allow prefetches of any outgoing link to one of a known set of origins or all links matching a CSS selector, or some other similar rule. Such a declaration is not a natural semantic fit with the `<link>` element, which declares a new non-rendered link to some given URL (its `href`). In such cases it might also be desirable to extract such a rule set to an external resource, if it is common to a large collection of documents.

> I have a couple of questions which probably just reveal my ignorance about the status quo here. Does a prefetch/prerender appear as normal web traffic to the destination or is it recogniseable as a prefetch (ie. what sort of effect does this have on analytics, if any)? Does this take into account prefetching/prerendering pages that immediately trigger an interaction with the user via the browser UI, like notifications, geolocation permissions etc? Can the prefetched origin get any other data about the user's current browsing context via js APIs way?

I think @domfarolino has answered this. Some information is certainly available in the prerender case but we have plans to limit it. In the prefetching case, less is available, though a prefetch that includes subresources may still reveal some information (for instance, I haven't checked Chromium's implementation but in the abstract a CSS stylesheet may be loaded or not loaded based on a media query).

> What kind of heuristics does the UA use to speculate, and are these transparent to authors and end users?

We're in the early days of exploring in Chrome what heuristics we think are best (effective, private, etc.). Some variables that a UA might hypothetically consider:

* author-supplied scores
* order of appearance in the document
* whether the link is in the viewport
* whether the cursor is near the link
* rendered size of the link
* per-origin state (e.g., has the user recently clicked this link or similar links when on this origin, subject to clearing site data, automatic expiry of this information, etc as the UA deems appropriate)
* coarse information about variables impacting the cost of the speculation (e.g., low device battery, metered network connection)

I expect a spirited discussion about many of these would be possible, and that different UAs (or possibly even different UA settings) may represent different views about what is best here, but I hope that this can largely not affect the author-facing API shape.

I think it would be sensible for browser vendors to explain how their heuristics work, but also to improve them over time. I don't know that there is normative text that could guarantee transparency, though.

> There's a bit in the privacy & security questionnaire about the UA's heuristics potentially revealing user data to the origin which could be a concern (particularly from a fingerprinting standpoint). Have you thought through what sort of rules a malicious origin might set in order to get as much leaked data as possible from the UA?

This is something that needs to be a key consideration when considering a heuristic. I think considering mostly or only information already available to the origin is a strong measure to mitigate this concern. For instance, any heuristic based on the current document, the scroll position, mouse position, recent activity on the current document's origin, does not reveal new information to such a malicious origin. Any heuristic that incorporated information not already available should be scrutinized to evaluate any additional security/privacy impact.

> Is there some way for the user to have the final say in whether/which origins can be prefetched? A permissions prompt is probably overkill, but maybe a browser setting.

I don't think Speculation Rules is dissimilar from Resource Hints in this way, so I would expect browsers to mirror their existing approach with Resource Hints in terms of whether they think a user-facing setting, whether global or per-origin, is useful (noting that sites can make other cross-origin requests using `fetch` or subresource requests).

**Comment by bokand** [comment]
> Does a prefetch/prerender appear as normal web traffic to the destination or is it recogniseable as a prefetch (ie. what sort of effect does this have on analytics, if any)?
>> Prerender and prefetch requests will be sent wth the Sec-Purpose: Prefetch header (this is not yet in our spec, but coming soon), so in that sense they are distinguishable. In terms of analytics, prefetchs will never run JavaScript. Prerenders will run JavaScript with the following caveats:
>>
>>* document.loadingMode will be prerendering so that JS can distinguish between normal and prerendering loading modes, as to perhaps not track analytics in prerendering mode

I'm not sure if we've decided that the loadingMode needs to be explicitly exposed to authors but we do have proposal for an explicit `document.prerendering` property which will let author script differentiate prerender-type loads from regular browsing. See:

  * https://github.com/jeremyroman/alternate-loading-modes/blob/main/prerendering-state.md
  * https://github.com/w3ctag/design-reviews/issues/613

**Comment by rhiaro** [comment]
> Thanks @jeremyroman and @domfarolino for your helpful responses to my questions.
>
> We can see you've thought about various privacy and security implications, but the spec so far doesn't have Privacy or Security Considerations sections, so don't forget to add those.
>
> We're still a little concerned about complexity for authors given the overlap with Resource Hints. We noticed that your ultimate target for this spec is WHATWG, but Resource Hints is going through the Web Performance WG. If you haven't already, it would be worth syncing with them and perhaps considering that as a venue for this work in future.
>
> Besides that, as this was an early review, we are content to close this and wish you luck with the continued incubation of this spec in WICG. We look forward to reviewing again at a later stage.
