### ISSUE TITLE
Should we handle the unload event for canceled prerendering

### ISSUE THREAD

**Issue by toyoshim** [WICG/nav-speculation#58]
https://github.com/jeremyroman/alternate-loading-modes/blob/main/browsing-context.md mentioned `beforeunload` but does not `unload`. Should we handle the `unload` event even in the case the prerendering is cancelled without being activated?

**Comment by domenic** [comment]
I think we have two choices on how to treat canceled prerendering:

- Like closing a tab: then we'd run https://html.spec.whatwg.org/multipage/window-object.html#close-a-browsing-context in full (including for descendants)
- Like a crash: then we wouldn't run anything

The first would be much preferable, if we can.

**Comment by toyoshim** [comment]
OK, thanks.
I will share this conclusion within the team, and try implementing it like closing a tab as we can as possible.

**Comment by domenic** [comment]
@mfalken, @jeremyroman, and I discussed this offline today and were thinking it might be OK to implement and spec this as https://html.spec.whatwg.org/multipage/window-object.html#a-browsing-context-is-discarded , with no events. (Basically like a crash.)

However, then we need to be especially clear on when cancelation happens. @mfalken is on point to help clarify what cases in Chrome's implementation do so, and how it would be observable (since apparently it currently depends on Chrome's IPC mechanism, which might not align very well with the natural place to spec such discarding).

**Comment by domenic** [comment]
This is done and in the spec!
